# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b062fd082682614160560d0f73b69be89c197dc1b146ece96c5970572d384f571452465bca776c347a4f9ab16c1adbf35ce189c7d8aefce383f01df50044a9fb

test:
  secret_key_base: f42119b3010e6b697a2a5790808f4817d89669332451cdd4fc448d951e413502b6c2bc52525c7255e0b4ade23477af28d3a3619dbdfc9f81eb8a54f729d2c43c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
